pipeline {
  agent any

  tools {
    jdk 'Java-11'
  }

  environment {
    JAVA_HOME = "%{tool 'Java-11'}"
  }

  stages {

    stage('Build') {
      steps {
        dir('EBC_app_grails') {
          sh "./grailsw clean"
          sh "./grailsw compile"
        }
      }
    }
    stage('Test') {
      steps {
        dir('EBC_app_grails') {
          sh "./grailsw test-app"
        }
      }
      post {
        always {
          dir('EBC_app_grails') {
            junit "build/test-results/test/TEST-*.xml"
          }
        }
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploying....'
      }
    }

  }

  post {
    always {
      slackSend(channel: '#general', message: "Construcción completada - Resultado: ${currentBuild.currentResult}")
    }
    success {
      echo "Proceso con éxito a las ${new Date()}"
    }
    failure {
      echo "Proceso con error a las ${new Date()}"
    }
  }
}
