pipeline {
  agent any

  tools {
    jdk 'Java-11'
  }

  environment {
    JAVA_HOME = "%{tool 'Java-11'}"
  }

  stages {

    stage('Build') {
      steps {
        dir('EBC_app_grails') {
          sh "./grailsw clean"
          sh "./grailsw compile"
        }
      }
    }
    stage('Test') {
      steps {
        dir('EBC_app_grails') {
          sh "./grailsw test-app"
        }
      }
      post {
        always {
          dir('EBC_app_grails') {
            junit "build/test-results/test/TEST-*.xml"
          }
        }
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploying....'
      }
    }

  }

  post {

    always {
      echo "Construcción completada: ${currentBuild.properties}"
    }
    success {
      slackSend(channel: '#general', color: "good", message: """
      Construcción *${currentBuild.fullDisplayName}* completada.\n
      Estado: *${currentBuild.currentResult}*\n
      Ver más en: <${env.BUILD_URL}|Aquí>\n
      Duración: ${currentBuild.durationString}\n
      Inicio: ${currentBuild.startTimeInMillis}
    """)
    }
    failure {
      slackSend(channel: '#general', color: "danger", message: """
      Construcción *${currentBuild.fullDisplayName}* completada.\n
      Estado: *${currentBuild.currentResult}*\n
      Ver más en: <${env.BUILD_URL}|Aquí>\n
      Duración: ${currentBuild.durationString}\n
      Inicio: ${currentBuild.startTimeInMillis}
    """)
    }
  }
}
